### ISSUE TITLE
use nvidia-image for gpu node detection

### ISSUE THREAD

**Issue by Bluemi** [curious-containers/curious-containers#27]

**Comment by Bluemi** [comment]
Implemented by [6fbd45f](https://github.com/curious-containers/cc-faice/commit/6fbd45f2274e92d9c94c7fceb5ac1c75fc25ab3d)

**Comment by Bluemi** [comment]
[6fbd45f](https://github.com/curious-containers/cc-faice/commit/6fbd45f2274e92d9c94c7fceb5ac1c75fc25ab3d) implements gpu detection for faice...

**Comment by Gnork** [comment]
Implement a "blacklist" feature, such that certain GPUs can be excluded if their IDs are listed.

**Comment by Bluemi** [comment]
[c7e39f4](https://github.com/curious-containers/cc-agency/commit/c7e39f43a5bf7847d985197fe882a09bb2e5d587) implements nvidia image node inspection.
Opening a new issue for the blacklist feature

**Comment by Bluemi** [comment]
Implemented automatic gpu detection in [73c834a](https://github.com/curious-containers/cc-agency/commit/73c834af261221a7bfac4de69b3e8da42b33601c)
Implemented blacklist feature in [c850537](https://github.com/curious-containers/cc-agency/commit/c850537a78c5bb7d291dd4523fa711321d0d8705)
