### ISSUE TITLE
Support CWL 1.1 Standard

### ISSUE THREAD

**Issue by Bluemi** [curious-containers/curious-containers#28]
Document all differences from the spec and wether they are intentional. If the they are intentional, list a reason. Intentional deviations must always be backwards compatible to the the CWL spec, such that the "cli" part of RED can still be used with CWLTool. If they are not intentional, create an issue.

- [ ] rework cwl types (expand short cwltypes e.g. "string[]?" to cwl type dictionary)

**Comment by Gnork** [comment]
[CWL 1.1](https://www.commonwl.org/v1.1/CommandLineTool.html) was released. For RED 9 we are dropping support for CWL 1.0 and instead move to CWL 1.1 which is future proof. This means the first stable release RED 10 will be based on the updated CWL standard. As a preparation for RED 10, RED 9 should support fully support CWL 1.1 and if we cannot support a certain part of the standard this should be documented.

**Comment by Bluemi** [comment]
will not be implemented
