### ISSUE TITLE
osx compatibily for faice

### ISSUE THREAD

**Issue by Bluemi** [curious-containers/curious-containers#29]

**Comment by Gnork** [comment]
Maybe implement a `faice hacks fix-fuse-in-docker-for-mac` command. This command could start a container with root user and the FUSE device mounted and use `chmod` to enable device access for others. This setting might be persistent for further container starts, such that FUSE devices can be used by experiment containers.

**Comment by Bluemi** [comment]
fuse mounts did now work.
caused by [this](https://github.com/docker/distribution/issues/2853) docker issue.
Fixed by  [30a032e](https://github.com/curious-containers/cc-faice/commit/30a032e6e0f153f705d52f8589be836d7acd43f0)
