### ISSUE TITLE
clean-up after refactoring

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#34]
* [x] remove "external_url" setting from conf schema
* [x] remove all code usage of "external_url"
* [x] remove unused _files_schemas from cc_agency/commons/schemas/callback.py
* [x] rename callback_schema and callback.py file to something more meaningful
* [x] remove build_dir.py and call to init_build_dir

**Comment by Bluemi** [comment]
solved by [8263748](https://github.com/curious-containers/cc-agency/commit/826374884ca8e08353ac2c53d8408d8e7d1f0f79) and [4c97650](https://github.com/curious-containers/cc-agency/commit/4c97650685db84beecc695faceac977a15806576)
