### ISSUE TITLE
let faice exec detect if --outputs is required based on red content

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#35]
Currently, `faice exec` will always set the --outputs flag when the "ccfaice" execution engine is specified. The rational is, that faice exec requires minimal flags when being called. To make `faice exec` work if no outputs are specified in the RED file, this should be detected automatically, such that no `--outputs` flag is set for `faice agent red`.

**Comment by Bluemi** [comment]
solved by [fcd7801](https://github.com/curious-containers/cc-faice/commit/fcd7801a3a7ae46b3e457d45ca794e8713d62cb1)
