### ISSUE TITLE
Docker stats

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#38]
After the execution of an experiment get the [Docker stats](https://docs.docker.com/engine/reference/commandline/stats/) from the exited container and provide the information for the user.

In CC-FAICE: add the information to the `--debug` result dictionary under a `docker_stats` keyword.

In CC-Agency add the information to the history entry, under a `docker_stats`keyword next to the `ccagent` keyword. For other history entries `docker_stats: None` should be set.

**Comment by Bluemi** [comment]
Implemented for faice by [05c158f](https://github.com/curious-containers/cc-faice/commit/05c158fd48eb65fd8c3382061cc253f3cd6e5580)

**Comment by Bluemi** [comment]
Implemented for agency by [e34ff2e](https://github.com/curious-containers/cc-agency/commit/e34ff2e54470f1f70dba17eb160a288b7c61dbf0)

**Comment by Gnork** [comment]
In the current implementation in cc-faice, the `docker_stats` entry will be overwritten for each batch. I think it should be stored in the dict in the `containers` list, next to `agentStdErr`, `agentStdOut`, `command` and so on. Also `docker_stats` should be renamed to `dockerStats` for consistency reasons.

**Comment by Bluemi** [comment]
Implemented for faice by [d39a07d](https://github.com/curious-containers/cc-faice/commit/d39a07dd8aa1dd57d7c640cb9201fc102bcb2388) and for agency by [b9eb453](https://github.com/curious-containers/cc-agency/commit/b9eb453b3d9a071ed931f417c606f99232a86b88).
