### ISSUE TITLE
Add support nvidia-container-toolkit

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#40]
The nvidia-docker runtime has been replaced by [nvidia-container-toolkit](https://github.com/NVIDIA/nvidia-docker) with the release of Docker 19.03. This is installed on deep.TEACHING cluster.

With nvidia-docker we had to specify `--runtime=nvidia`, a setting that is not supported anymore and will throw an error.

We need to add support for this new behaviour, while also keeping support for the old variant. Maybe the `Runtimes` list from `docker system info` is useful to solve this. Maybe this information is accessible via docker-py.

**Comment by Bluemi** [comment]
- Implemented for agency in [45dcaf4](https://github.com/curious-containers/cc-agency/commit/45dcaf468324c79d2787fd356c8176625114368f)
- Implemented for faice in [aec7dc1](https://github.com/curious-containers/cc-faice/commit/aec7dc101b21607ea31b25eb3d87c3204394c296) and [23088e8](https://github.com/curious-containers/cc-faice/commit/23088e8a2a1f7d8ace72c4b4f4528f4736414e22)
- Tools in cc-core implemented in [820fb8a](https://github.com/curious-containers/cc-core/commit/820fb8a1c6dc414798755f77284ef9413249e15c)
