### ISSUE TITLE
Automatic deletion of old images

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#41]
Implement a new feature, where old images, that have NOT BEEN USED for a certain time, are deleted from a cluster node to free up space. The time for deletion in seconds should be setting in the ccagency.yml config file.

**Comment by Bluemi** [comment]
implemented by [3d2d4a1](https://github.com/curious-containers/cc-agency/commit/3d2d4a1927bb309ea1db3a09fccc5868e1355e19)
fixed by [60e6d8f](https://github.com/curious-containers/cc-agency/commit/60e6d8f4c86a97ca388fcd552954b0032fdaeeed)
