### ISSUE TITLE
Remove faice file-server

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#42]
The `faice file-server` command is only used in the RED Beginner's Guide. We should remove the file-server feature and its flask dependency. We then remove the section from the RED Beginner's Guide where output connectors are specified.

As an alternative, we should write an additional advanced guide, that requires the user to setup an SSH server first, which is then used for connector inputs and outputs.

**Comment by Bluemi** [comment]
Removed with [e7fa67f](https://github.com/curious-containers/cc-faice/commit/e7fa67f91e006ba1ce85c132c3dd49dbc579caae)
