### ISSUE TITLE
Too many type: 'null' entries in jsonschemas

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#46]
The function `cc_core.commons.schemas.schema_transform.transform` generates `type: 'null'` entries for all keys that are not in the `required` list of a jsonschema. In some cases, duplicates of this entry can be found in the schema.

This behaviour must be fixed and a test for these cases should be added in `tests.commons.test_schema_transform`.

**Comment by Bluemi** [comment]
Fixed by [8169fb4](https://github.com/curious-containers/cc-core/commit/8169fb4f7f3d250971d0fd8d0a2b30e54321f84f)

+ test_null_values()
