### ISSUE TITLE
Standardize token authentication

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#47]
Currently, token authentication is implemented in a custom way. Therefore, a standard way to do this must be researched and implemented.

Remarks:

1. This will probably involve the usage of authentication cookies that is sent back to user with a successful username+password auth. The cookie can then be send to the server for further authentication without the requirement of sending username+password again.

2. A token should be coupled to a certain IP address and username. The token should be persisted in the database across requests and if a valid token is available it will be reused. This avoids having an increasing number of open "sessions".

**Comment by Bluemi** [comment]
Implemented in [31bb935](https://github.com/curious-containers/cc-agency/commit/31bb935dbb7024327a8eb414edbf87a07e8ce46a) and [bfaa25b](https://github.com/curious-containers/cc-agency/commit/bfaa25ba8cb52d827a0a0bfabbffe9346f5e42c4)
