### ISSUE TITLE
Server-Rendered HTML UI

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#48]
Details will be discussed later.

**Comment by Domprobst** [comment]
Using vue.js to create a SPA Web UI in https://github.com/curious-containers/cc-agency-ui

**Comment by Domprobst** [comment]
The existing cc-agency broker will manage all data and authentication http requests. The Web UI should have the flexibility to be deployed on either the same server or a separate one; hence, enabling CORS becomes essential. However, this creates a problem. In the context of Flask, when origins are configured using the wildcard "*" (as detailed in the Flask-CORS documentation: https://flask-cors.readthedocs.io/en/latest/api.html), it restricts the submission of cookies and credentials across domains.

Currently, the authentication relies on the Set-Cookie header. With the implementation of the SPA UI, this must therefore be adapted. A viable approach is to incorporate JWT (https://flask-jwt-extended.readthedocs.io/en/stable/index.html). This is widely used and is very suitable for the use case.

**Comment by Domprobst** [comment]
Released with cc-agency version 9.3.0. See [CC-Agency-UI](https://github.com/curious-containers/cc-agency-ui) for details.
