### ISSUE TITLE
faice exec does not show ccagency error messages

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#56]
Currently, executing `faice exec` sends a red file to cc-agency, if this execution engine is specified. If a 400 BadRequest happens, the description message of CC-Agency is not displayed. This is also true if using the `--debug` flag.

Currently the error messages are in HTML format. It would probably be best to change CC-Agency, to send these error messages in JSON format. This would allow FAICE and other applications to easily parse and display them.

**Comment by Bluemi** [comment]
- implemented for cc-agency in [5bc836b](https://github.com/curious-containers/cc-agency/commit/5bc836b62df03b5de64cb077b64b3081e75ae703)
- implemented for cc-faice in [f60a9a5](https://github.com/curious-containers/cc-faice/commit/f60a9a510f78921fd566f32cc75743f3355a5c48)
