### ISSUE TITLE
Check connectivity in validate functions

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#58]
If someone uses red-connector-ssh, they could easily specify wrong access information, leading to a failure. This is especially problematic, if the connector is only used to send a file or directory, such that the connector is executed after the application finishes, which might take a long time, to then just produce a failure.

A connectivity check should be implemented in all `validate` functions, such that potential connectivity errors are visible immediately, before running the application.

**Comment by Bluemi** [comment]
Implemented by [b7dbe7a](https://github.com/curious-containers/red-connector-ssh/commit/b7dbe7a98817cf2c38db6dfd2f930c5805c1b712)
