### ISSUE TITLE
Remove unnecessary RED parts before checking for variables

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#61]
If the `faice agent red` command is executed without the `--outputs` the contents of the `outputs` section of the RED file is not used for the experiment, but the program will still ask for undefined values of variables for this section.

The program should remove RED sections that are not required before checking for variables.

**Comment by Bluemi** [comment]
Closing this issue, because the `--outputs` flag is not implemented for the 8.2 RED client of faice.
